resources:
  io_manager:
    config:
      base_path: "data/processed"

execution:
  config:
    multiprocess:
      tag_concurrency_limits:
        - key: "io_manager"
          limit: 1

ops:
  config:
    train_random_forest:
      n_estimators: 100